# Generated by Django 4.2.30 on 2026-05-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=100)),
                ('preorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.customer')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.worker')),
            ],
        ),
    ]
