# Generated by Django 4.2.30 on 2026-05-19 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0002_assigned_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='work_type',
        ),
        migrations.AddField(
            model_name='worker',
            name='personal_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assigned_work',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_work', to='myprojectapp.worker'),
        ),
    ]
