# Generated by Django 4.2.30 on 2026-05-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0003_remove_worker_work_type_worker_personal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='work_type',
            field=models.CharField(choices=[('designer', 'Designer'), ('tailor', 'Tailor'), ('embroidery', 'Embroidery'), ('packing', 'Packing')], default='tailor', max_length=100),
        ),
    ]
