# Generated by Django 4.2.30 on 2026-05-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0004_worker_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned_work',
            name='work_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
