# Generated by Django 4.2.30 on 2026-07-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0005_assigned_work_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='work_type',
            field=models.CharField(choices=[('cutwork/Embroidary', 'cutwork/Embroidary'), ('Handwork/Applique', 'Handwork/Applique'), ('Readymade', 'Readymade')], default='tailor', max_length=100),
        ),
    ]
